name: "Context examples"

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      env:
        MY_ACTION: ${{ github.action }}
      - name: "My step"
        run: echo "Hello! $MY_ACTION"